language: cpp
compiler:
  - gcc
  - clang

install:
  - sudo apt-get install cmake libboost-dev libsdl1.2-dev
  
  
before_script:
  - mkdir _build
  - cd _build
  
script:
  - cmake ../src
  - make -j4
    
  
